### ISSUE TITLE
example/client.elm and example/server.elm need Capitalized file names

### ISSUE THREAD

**Issue by billstclair** [RGBboy/websocket-server#1]
When I built the example on my Mac, using:

    npm run build:example

it worked fine. On my Ubuntu server, however, I got an error that the file `example/Client.elm` did not exist. This is because the file is named `example/client.elm`. It and `example/server.elm` need to have their file names Capitalized to `Client.elm` and `Server.elm`. After doing that, the example works on my Ubuntu server.

This is such a trivial fix that I decided reporting it as an issue made more sense than creating a pull request.

**Comment by RGBboy** [comment]
Just fixed it. Thanks for pointing that out.
